Movies = [
    {"Movie": "Batman - The Movie", "Length": "1:44:53"},
    {"Movie": "Big Trouble in Little China", "Length": "1:39:49"},
    {"Movie": "Birdemic - Shock and Terror", "Length": "1:33:29"},
    {"Movie": "Black Rain", "Length": "2:05:18"},
    {"Movie": "Blade", "Length": "2:00:15"},
    {"Movie": "Bloodsport", "Length": "1:32:19"},
    {"Movie": "Captain America", "Length": "1:37:04"},
    {"Movie": "Child's Play", "Length": "1:27:12"},
    {"Movie": "Child's Play 2", "Length": "1:23:50"},
    {"Movie": "Child's Play 3", "Length": "1:29:39"},
    {"Movie": "Cobra", "Length": "1:27:03"},
    {"Movie": "Commando", "Length": "1:30:15"},
    {"Movie": "ConAir", "Length": "1:55:26"},
    {"Movie": "Conan", "Length": "2:10:31"},
    {"Movie": "Creepshow", "Length": "2:00:28"},
    {"Movie": "Cybernator", "Length": "1:25:38"},
    {"Movie": "Death Spa", "Length": "1:27:26"},
    {"Movie": "Demolition Man", "Length": "1:55:02"},
    {"Movie": "Die Hard", "Length": "2:12:07"},
    {"Movie": "Dragonball Evolution", "Length": "1:25:26"},
    {"Movie": "E.T. The Extra Terrestrial", "Length": "1:54:35"},
    {"Movie": "Ernest Saves Christmas", "Length": "1:31:29"},
    {"Movie": "Escape From New York", "Length": "1:39:28"},
    {"Movie": "Excessive Force II - Force on Force", "Length": "1:27:54"},
    {"Movie": "Fire in the Sky", "Length": "1:49:19"},
    {"Movie": "Friday the 13th Part 2", "Length": "1:26:59"},
    {"Movie": "Friday the 13th Part III", "Length": "1:35:14"},
    {"Movie": "Friday the 13th", "Length": "1:35:27"},
    {"Movie": "Ghostbusters", "Length": "1:45:08"},
    {"Movie": "Gremlins 2 - The New Batch", "Length": "1:46:26"},
    {"Movie": "Gymkata", "Length": "1:29:38"},
    {"Movie": "Hard to Kill", "Length": "1:35:38"},
    {"Movie": "Harry Potter and the Chamber of Secrets", "Length": "2:40:58"},
    {"Movie": "Harry Potter and the Sourcerers Stone", "Length": "2:32:21"},
    {"Movie": "Harry and the Hendersons", "Length": "1:50:52"},
    {"Movie": "Harry Potter and the Deathly Hallows Part 1", "Length": "2:26:05"},
    {"Movie": "Harry Potter and the Deathly Hallows Part 2", "Length": "2:10:26"},
    {"Movie": "Harry Potter and the Goblet of Fire", "Length": "2:37:05"},
    {"Movie": "Harry Potter and the Half-Blood Prince", "Length": "2:33:31"},
    {"Movie": "Harry Potter and the Order of the Pheonix", "Length": "2:18:14"},
    {"Movie": "Harry Potter and the Prisoner of Azkaban", "Length": "2:21:42"},
    {"Movie": "Highlander", "Length": "1:56:38"},
    {"Movie": "Hitman Agent 47", "Length": "1:36:16"},
    {"Movie": "Hobo with a Shotgun", "Length": "1:26:37"},
    {"Movie": "Hollywood Cop", "Length": "1:39:46"},
    {"Movie": "Home Alone", "Length": "1:42:50"},
    {"Movie": "Ice Cream Man", "Length": "1:23:46"},
    {"Movie": "Jingle All the Way", "Length": "1:33:44"},
    {"Movie": "John Wick", "Length": "1:41:11"},
    {"Movie": "Johnny Mnemonic", "Length": "1:36:42"},
    {"Movie": "Judge Dredd", "Length": "1:36:11"},
    {"Movie": "Kazaam", "Length": "1:33:34"},
    {"Movie": "Killer Klowns From Outer Space", "Length": "1:26:10"},
    {"Movie": "Killing American Style", "Length": "1:40:54"},
    {"Movie": "Kindergarten Cop", "Length": "1:51:14"},
    {"Movie": "Last Action Hero", "Length": "2:10:54"},
    {"Movie": "Leprechaun", "Length": "1:31:25"},
    {"Movie": "Leprechaun 2", "Length": "1:25:23"},
    {"Movie": "Leprechaun 3", "Length": "1:33:16"},
    {"Movie": "Leprechaun 4 - In Space", "Length": "1:35:16"},
    {"Movie": "Mac and Me", "Length": "1:39:22"},
    {"Movie": "Miami Connection", "Length": "1:26:33"},
    {"Movie": "Mortal Kombat Annihilation", "Length": "1:35:44"},
    {"Movie": "Outbreak", "Length": "2:08:12"},
    {"Movie": "Police Story 4 - First Strike", "Length": "1:23:50"},
    {"Movie": "Rampage", "Length": "1:47:16"},
    {"Movie": "Resident Evil Apocalypse", "Length": "1:33:48"},
    {"Movie": "RoboCop 2", "Length": "1:56:40"},
    {"Movie": "RoboCop 3", "Length": "1:44:50"},
    {"Movie": "Rumble in the Bronx", "Length": "1:29:32"},
    {"Movie": "Samurai Cop", "Length": "1:36:32"},
    {"Movie": "Santa with Muscles", "Length": "1:37:40"},
    {"Movie": "Short Circuit", "Length": "1:38:34"},
    {"Movie": "Showgirls", "Length": "2:11:22"},
    {"Movie": "Silent Night Deadly Night 2", "Length": "1:28:22"},
    {"Movie": "Silent Night Deadly Night", "Length": "1:24:55"},
    {"Movie": "Silent Night Deadly Night 3 - Better Watch Out", "Length": "1:29:56"},
    {"Movie": "Small Soldiers", "Length": "1:49:47"},
    {"Movie": "Sonic the Hedgehog", "Length": "1:38:53"},
    {"Movie": "Star Wars Episode I - The Phantom Menace", "Length": "2:16:11"},
    {"Movie": "Star Wars Episode II - Attack of the Clones", "Length": "2:22:29"},
    {"Movie": "Star Wars Episode III - Revenge of the Sith", "Length": "2:20:06"},
    {"Movie": "Star Wars Episode IV - A New Hope", "Length": "2:04:44"},
    {"Movie": "Star Wars Episode V - The Empire Strikes Back", "Length": "2:07:22"},
    {"Movie": "Star Wars Episode VI - Return of the Jedi", "Length": "2:14:47"},
    {"Movie": "Starship Troopers", "Length": "2:09:37"},
    {"Movie": "Tammy and the T-Rex", "Length": "1:30:51"},
    {"Movie": "Teenage Mutant Ninja Turtles 2 - The Secret of the Ooze", "Length": "1:28:42"},
    {"Movie": "Teenage Mutant Ninja Turtles 3 - The Sacred Scroll of Death", "Length": "1:36:13"},
    {"Movie": "Teenage Mutant Ninja Turtles - The Movie", "Length": "1:33:34"},
    {"Movie": "Terminator 2 - Judgment Day", "Length": "2:17:08"},
    {"Movie": "Thankskilling", "Length": "1:06:42"},
    {"Movie": "The Godfather", "Length": "2:57:09"},
    {"Movie": "The Mummy", "Length": "2:04:49"},
    {"Movie": "The Return of the Living Dead", "Length": "1:30:30"},
    {"Movie": "The Santa Clause", "Length": "1:37:08"},
    {"Movie": "The Warriors", "Length": "1:33:59"},
    {"Movie": "The Lord of the Rings - The Fellowship of the Ring", "Length": "3:48:11"},
    {"Movie": "The Lord of the Rings - The Return of the King", "Length": "4:23:10"},
    {"Movie": "The Lord of the Rings - The Two Towers", "Length": "3:55:24"},
    {"Movie": "The Perfect Weapon", "Length": "1:24:59"},
    {"Movie": "The Running Man", "Length": "1:40:43"},
    {"Movie": "The Terminator", "Length": "1:47:24"},
    {"Movie": "The Wicker Man", "Length": "1:41:55"},
    {"Movie": "They Live", "Length": "1:34:07"},
    {"Movie": "Total Recall", "Length": "1:53:31"},
    {"Movie": "Tremors", "Length": "1:36:00"},
    {"Movie": "Troll", "Length": "1:22:35"},
    {"Movie": "True Lies", "Length": "2:20:58"},
    {"Movie": "Twisted Pair", "Length": "1:28:39"},
    {"Movie": "Universal Soldier", "Length": "1:43:43"},
    {"Movie": "X2 - X-Men United", "Length": "2:13:47"},
    {"Movie": "X-Men - The Last Stand", "Length": "1:44:05"},
    {"Movie": "X-Men", "Length": "1:44:25"}
]